// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: replica/v1/replica.proto

package replica

import (
	object "github.com/rotationalio/honu/object"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status indicates what state the synchronization is in between peers, allowing
// the replicas to coordinate between multiple sync messages in a grpc stream.
type Sync_Status int32

const (
	Sync_UNKNOWN  Sync_Status = 0 // Should not be used as a status
	Sync_CHECK    Sync_Status = 1 // Sync contains version information only
	Sync_REPAIR   Sync_Status = 2 // Sync contains object data information
	Sync_COMPLETE Sync_Status = 3 // Sync contains no object information, ready to end Gossip
	Sync_ERROR    Sync_Status = 4 // Sync contains object-specific error information
)

// Enum value maps for Sync_Status.
var (
	Sync_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "CHECK",
		2: "REPAIR",
		3: "COMPLETE",
		4: "ERROR",
	}
	Sync_Status_value = map[string]int32{
		"UNKNOWN":  0,
		"CHECK":    1,
		"REPAIR":   2,
		"COMPLETE": 3,
		"ERROR":    4,
	}
)

func (x Sync_Status) Enum() *Sync_Status {
	p := new(Sync_Status)
	*p = x
	return p
}

func (x Sync_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sync_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_replica_v1_replica_proto_enumTypes[0].Descriptor()
}

func (Sync_Status) Type() protoreflect.EnumType {
	return &file_replica_v1_replica_proto_enumTypes[0]
}

func (x Sync_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sync_Status.Descriptor instead.
func (Sync_Status) EnumDescriptor() ([]byte, []int) {
	return file_replica_v1_replica_proto_rawDescGZIP(), []int{0, 0}
}

// Sync messages allow replicas to exchange information in a bidirectional stream.
// Because Sync messages are sent in the stream, there are different synchronization
// types. A "check" synchronization sends only the version vector without data,
// requesting the remote peer to check if they have a later version, and if so, return
// it. A "repair" synchronization sends object data back if the sender's version is
// later. A "complete" synchronization indicates that the sender is fully synchronized,
// and an "error" synchronization message says that there was some failure repairing
// the specified version vector.
type Sync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Sync_Status    `protobuf:"varint,1,opt,name=status,proto3,enum=honu.replica.v1.Sync_Status" json:"status,omitempty"` // The status/type of sync messages
	Object *object.Object `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`                                   // The object being synchronized
	Error  string         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                     // Error information if the object failed to sync
}

func (x *Sync) Reset() {
	*x = Sync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replica_v1_replica_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync) ProtoMessage() {}

func (x *Sync) ProtoReflect() protoreflect.Message {
	mi := &file_replica_v1_replica_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync.ProtoReflect.Descriptor instead.
func (*Sync) Descriptor() ([]byte, []int) {
	return file_replica_v1_replica_proto_rawDescGZIP(), []int{0}
}

func (x *Sync) GetStatus() Sync_Status {
	if x != nil {
		return x.Status
	}
	return Sync_UNKNOWN
}

func (x *Sync) GetObject() *object.Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *Sync) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_replica_v1_replica_proto protoreflect.FileDescriptor

var file_replica_v1_replica_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x68, 0x6f, 0x6e, 0x75,
	0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x2e, 0x76, 0x31, 0x1a, 0x16, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xc9, 0x01, 0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x34, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x68,
	0x6f, 0x6e, 0x75, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x79, 0x6e, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x68, 0x6f, 0x6e, 0x75, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x45, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45,
	0x50, 0x41, 0x49, 0x52, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45,
	0x54, 0x45, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x32,
	0x4b, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c,
	0x0a, 0x06, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x12, 0x15, 0x2e, 0x68, 0x6f, 0x6e, 0x75, 0x2e,
	0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x1a,
	0x15, 0x2e, 0x68, 0x6f, 0x6e, 0x75, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x26, 0x5a, 0x24,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x69, 0x6f, 0x2f, 0x68, 0x6f, 0x6e, 0x75, 0x2f, 0x72, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_replica_v1_replica_proto_rawDescOnce sync.Once
	file_replica_v1_replica_proto_rawDescData = file_replica_v1_replica_proto_rawDesc
)

func file_replica_v1_replica_proto_rawDescGZIP() []byte {
	file_replica_v1_replica_proto_rawDescOnce.Do(func() {
		file_replica_v1_replica_proto_rawDescData = protoimpl.X.CompressGZIP(file_replica_v1_replica_proto_rawDescData)
	})
	return file_replica_v1_replica_proto_rawDescData
}

var file_replica_v1_replica_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_replica_v1_replica_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_replica_v1_replica_proto_goTypes = []interface{}{
	(Sync_Status)(0),      // 0: honu.replica.v1.Sync.Status
	(*Sync)(nil),          // 1: honu.replica.v1.Sync
	(*object.Object)(nil), // 2: honu.object.v1.Object
}
var file_replica_v1_replica_proto_depIdxs = []int32{
	0, // 0: honu.replica.v1.Sync.status:type_name -> honu.replica.v1.Sync.Status
	2, // 1: honu.replica.v1.Sync.object:type_name -> honu.object.v1.Object
	1, // 2: honu.replica.v1.Replication.Gossip:input_type -> honu.replica.v1.Sync
	1, // 3: honu.replica.v1.Replication.Gossip:output_type -> honu.replica.v1.Sync
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_replica_v1_replica_proto_init() }
func file_replica_v1_replica_proto_init() {
	if File_replica_v1_replica_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_replica_v1_replica_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_replica_v1_replica_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_replica_v1_replica_proto_goTypes,
		DependencyIndexes: file_replica_v1_replica_proto_depIdxs,
		EnumInfos:         file_replica_v1_replica_proto_enumTypes,
		MessageInfos:      file_replica_v1_replica_proto_msgTypes,
	}.Build()
	File_replica_v1_replica_proto = out.File
	file_replica_v1_replica_proto_rawDesc = nil
	file_replica_v1_replica_proto_goTypes = nil
	file_replica_v1_replica_proto_depIdxs = nil
}
